### ISSUE TITLE
`fil_actor_verifreg_state::{v8, v9}` are needed for nv17 state migration

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/fil-actor-states#112]
**Issue summary**

See 
https://github.com/filecoin-project/go-state-types/blob/master/builtin/v9/migration/datacap.go#L6
and 
https://github.com/filecoin-project/go-state-types/blob/master/builtin/v9/migration/datacap.go#L17

**Other information and links**

https://github.com/ChainSafe/forest/issues/2801

**Comment by sudo-shashank** [comment]
already available https://github.com/ChainSafe/fil-actor-states/tree/main/actors/verifreg/src
