### ISSUE TITLE
Implement APIs for v0 init actor state

### ISSUE THREAD

**Issue by creativcoder** [ChainSafe/fil-actor-states#137]
**Issue summary**

Part of https://github.com/ChainSafe/forest/pull/2913

**Other information and links**

**Comment by lemmih** [comment]
What API do you need?

**Comment by creativcoder** [comment]
I don't think we would need it at the moment, as the issue is somewhere else. We're still investigating the issue with loading genesis state root and figured there's differences in underlying ipld instance that gets returned.
