### ISSUE TITLE
Implement Amt diff lib

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/fil-actor-states#143]
**Issue summary**

An Amt diff lib is used for implementing miner actor v8 -> v9 state migration, we need to 
- [ ] Find an existing implementation or alternative in rust ecosystem
- [ ] Or implement on our own with parity tests

https://github.com/filecoin-project/go-state-types/blob/master/builtin/v9/migration/miner.go#L278
```go
// we have previous work, but the AMT has changed -- diff them
diffs, err := amt.Diff(ctx, store, store, prevInRoot, inRoot, amt.UseTreeBitWidth(miner9.SectorsAmtBitwidth))
```

https://github.com/filecoin-project/go-amt-ipld/blob/master/diff.go#L42
```go
// Diff returns a set of changes that transform node 'a' into node 'b'. opts are applied to both prev and cur.
func Diff(ctx context.Context, prevBs, curBs cbor.IpldStore, prev, cur cid.Cid, opts ...Option) ([]*Change, error) {
}
```

**Other information and links**

As part of https://github.com/ChainSafe/forest/issues/2801

**Comment by hanabi1224** [comment]
@lemmih @LesnyRumcajs I'm not able to find anything similar in https://docs.rs/fvm_ipld_amt/latest/fvm_ipld_amt/  Let me know if you happen to know an existing implementation or an alternative, otherwise I will implement it in this repo.

**Comment by lemmih** [comment]
Yeah, I doubt a Rust version of this exists. You probably have to port it from scratch.

**Comment by hanabi1224** [comment]
@lemmih PR created in `ref-fvm` repo: https://github.com/filecoin-project/ref-fvm/pull/1788  Before it's accepted, should I cargo patch `fvm_ipld_amt` to unblock my nv17 state migration work or port the `fvm_ipld_amt` as a module of `fil_actors_shared`?
