### ISSUE TITLE
Discussion from #177

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/fil-actor-states#195]
> The builtin-actors crates are not supported (they're used to generate WASM code once and then abandoned). This is a problem for us since we need to access the data structures for the actors. So, we copy all the code from the builtin-actors and then we remove the smart-contract implementations while keeping the data structures. Figuring out what code can be deleted (since it'll be run via WASM) and what code should be kept isn't a completely trivial task, though.

Thanks, this helps me understand the bigger picture here.

> Figuring out what code can be deleted (since it'll be run via WASM) and what code should be kept isn't a completely trivial task, though.

If we only need the data structures, why do we have to do any thinking at all? Just keep the code if it starts with `pub struct`?
Could we not automate the farming and deduplication of the structs?

_Originally posted by @aatifsyed in https://github.com/ChainSafe/fil-actor-states/issues/177#issuecomment-1792109581_

**Comment by aatifsyed** [comment]
cc @sudo-shashank @lemmih

**Comment by LesnyRumcajs** [comment]
@aatifsyed @lemmih What do we do with this issue? Is it actionable in any way?
