### ISSUE TITLE
Fix Policy serialisation to TOML/JSON

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/fil-actor-states#2]
I found that [current](https://github.com/filecoin-project/ref-fvm/blob/master/shared/src/bigint/bigint_ser.rs) (de)serialisers for BigInt [fields](https://github.com/filecoin-project/builtin-actors/blob/8ca492449e0514c20d3578502ae7a9645fc91518/runtime/src/runtime/policy.rs#L141-L142) in the Policy struct are not `String` friendly. 

```
thread 'cli::config_cmd::tests::given_default_configuration_should_print_valid_toml' panicked at 'Invalid configuration!: Error { inner: ErrorInner { kind: Custom, line: Some(206), col: 0, at: Some(5985), message: "invalid type: sequence, expected a byte array", key: ["chain", "policy", "minimum_verified_allocation_size"] } }', forest/cli/src/cli/config_cmd.rs:44:14
```

In other words, the serialisation-deserialisation round-trip fails for them (I tested on both toml and json). If we want to re-use the Policy struct from builtin-actors, we should introduce an alternative [serialiser](https://github.com/ChainSafe/forest/blob/f0ac5b50f91eb23a35e1c2e533cb5e65ffe7b542/utils/json/src/bigint.rs#L4) which we use in Forest or something that can be serialized to a human-readable file.

**Comment by hanabi1224** [comment]
There's a regression on the latest `main`. The same error happen again. See https://github.com/ChainSafe/forest/actions/runs/4463848459/jobs/7839453712?pr=2685#step:7:1561
