### ISSUE TITLE
Prepare for publish

### ISSUE THREAD

**Issue by sudo-shashank** [ChainSafe/fil-actor-states#32]
Todo list before publishing to crates.io
- [X] Update the package description of every crate to be ready for publishing
- [X] Some crates have alpha in their version.
- [X] Some shared dependencies are workspace dependencies and some are not.
- [X] Move fil_utils to a fil_actor_interface or somewhere better

**Comment by hanabi1224** [comment]
I think we also need below tasks done before publishing the crates
1. Build and test with stable rust on CI
2. Cleanup all build warnings
3. Cleanup unused dependencies
