### ISSUE TITLE
Move extra methods from actor states

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/fil-actor-states#338]
**Issue summary**

Actor state files must remain as close to their source as possible. They should not be extended by additional methods directly like in https://github.com/ChainSafe/fil-actor-states/pull/290. All such occurrences should be moved to, e.g., Forest shim or extension traits.

This is should lower the upgrade burden (less manual copy-pasting from our own definitions - only from the `builtin-actors`) and manage our expectations for the given methods (`builtin-actors` code is the holy grail and we should assume it's correct, otherwise it's a massive issue for Filecoin networks).

**Other information and links**

**Comment by LesnyRumcajs** [comment]
@sudo-shashank Could you please identify which methods are "our own" and should be migrated elsewhere?

**Comment by sudo-shashank** [comment]
> @sudo-shashank Could you please identify which methods are "our own" and should be migrated elsewhere?

okay sure
