### ISSUE TITLE
Implement types module for `fil_actor_evm_state` v12

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/fil-actor-states#347]
**Issue summary**

To implement the `EthTraceBlock` RPC method we need to access some types in `fil_actor_evm_state` v12.

- `ConstructorParams`
- `GetStorageAtParams`
- `DelegateCallParams`
- `GetBytecodeReturn`

Consider implementing type aliases as well.

**Other information and links**

https://github.com/filecoin-project/go-state-types/blob/master/builtin/v12/evm/evm_types.go

**Comment by sudo-shashank** [comment]
@elmattic these are present in `/actors/evm/src/<Version>/types.rs`
https://github.com/ChainSafe/fil-actor-states/blob/main/actors/evm/src/v12/types.rs

**Comment by elmattic** [comment]
My bad, let's close this one.
