### ISSUE TITLE
Align actor dependencies versioning with the builtin-actors

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/fil-actor-states#58]
We must align the dependencies to have them on par with the builtin-actors. Otherwise, we end up in a situation where we cannot resolve a delegated address as the method accepts only FVM2 `Address`, and the conversion is not possible. https://github.com/ChainSafe/fil-actor-states/blob/main/init_v10/src/state.rs#L78

So, taking as an example this Cargo file https://github.com/ChainSafe/fil-actor-states/blob/main/init_v10/Cargo.toml

The versions there must match whatever was used at the time of the release of v10 actors in https://github.com/filecoin-project/builtin-actors/blob/master/actors/init/Cargo.toml#L19, most notably FVM3, which is not compatible with the FVM2.

The same goes for all other actors.

The priority is to have the v10 dependencies aligned. Later, we should ensure that v9 and v8 also use the correct versioning.

**Comment by lemmih** [comment]
@sudo-shashank if you could have a look that'd be fantastic, unfortunately it's a blocker, at least having fvm3 in v10 actors.

**Comment by sudo-shashank** [comment]
all versions are aligned, hence closing this issue
